# Generated by Django 3.2.3 on 2021-05-19 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.AddField(
            model_name='bugreport',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.bugtopics'),
        ),
    ]
