# Generated by Django 3.2.3 on 2021-05-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20210520_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fname',
            field=models.TextField(default='default'),
        ),
        migrations.DeleteModel(
            name='bugReport',
        ),
        migrations.DeleteModel(
            name='bugTopics',
        ),
    ]
