# Generated by Django 3.2.3 on 2021-05-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20210519_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fname',
            new_name='name',
        ),
    ]
