# Generated by Django 3.2.3 on 2021-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_bugreport_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
